# Generated by Django 5.2.4 on 2025-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('amendment_number', models.AutoField(primary_key=True, serialize=False)),
                ('amendment_text', models.TextField()),
                ('deprecated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionHistory',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('proposed_at', models.TimeField()),
                ('polls_closed_at', models.TimeField()),
                ('passed', models.BooleanField(null=True)),
                ('proposal_text', models.TextField()),
                ('proposal_function_key', models.TextField()),
                ('proposal_data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.TextField()),
                ('can_vote', models.BooleanField(default=True)),
                ('vote_fraction', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('can_vote', models.BooleanField(default=True)),
                ('vote_fraction', models.FloatField(default=1.0)),
                ('registration', models.TextField(default='SchmuckServer')),
                ('is_god_king', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VotingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_cooldown', models.TimeField()),
                ('accepting_new_registrations', models.BooleanField()),
                ('voting_style', models.CharField()),
                ('poll_availability_period', models.TimeField()),
            ],
        ),
    ]
