# Generated by Django 5.2.4 on 2025-07-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingrules',
            name='tiebreaking_method',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
