# Generated by Django 5.2.4 on 2025-07-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_votingrules_tiebreaking_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionhistory',
            name='is_rigged',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingrules',
            name='is_electoral_college_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingrules',
            name='is_sending_notifications',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votingrules',
            name='poll_availability_period',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='votingrules',
            name='registration_cooldown',
            field=models.DateTimeField(),
        ),
    ]
