# Generated by Django 5.2.4 on 2025-07-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_provisionhistory_is_rigged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='provisionhistory',
            name='message_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provisionhistory',
            name='proposed_by_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='vetoes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='is_rigged',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='polls_closed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='proposal_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='proposed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roles',
            name='vote_fraction',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='votingrules',
            name='tiebreaking_method',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='votingrules',
            name='voting_style',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function_key', models.TextField(blank=True, null=True)),
                ('follows', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votingapp.category')),
            ],
        ),
    ]
