# Generated by Django 5.2.4 on 2025-07-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0004_remove_users_id_provisionhistory_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
