# Generated by Django 5.2.4 on 2025-07-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='words',
        ),
    ]
