# Generated by Django 5.2.4 on 2025-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0006_rename_name_category_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionhistory',
            old_name='polls_closed_at',
            new_name='polls_close_at',
        ),
        migrations.RemoveField(
            model_name='provisionhistory',
            name='proposal_data',
        ),
        migrations.RemoveField(
            model_name='provisionhistory',
            name='proposal_text',
        ),
        migrations.RemoveField(
            model_name='votingrules',
            name='poll_availability_period',
        ),
        migrations.RemoveField(
            model_name='votingrules',
            name='registration_cooldown',
        ),
        migrations.AddField(
            model_name='provisionhistory',
            name='value1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionhistory',
            name='value2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votingrules',
            name='poll_availability_hours',
            field=models.SmallIntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingrules',
            name='registration_cooldown_hours',
            field=models.SmallIntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='message_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
