# Generated by Django 5.2.4 on 2025-07-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0007_rename_polls_closed_at_provisionhistory_polls_close_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='function_key',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='message_id',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='value1',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provisionhistory',
            name='value2',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
