# Generated by Django 5.2.4 on 2025-07-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0008_allowedaccess_alter_category_function_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionhistory',
            old_name='proposal_function_key',
            new_name='function_key',
        ),
        migrations.AddField(
            model_name='constitution',
            name='message_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
