# Generated by Django 5.2.4 on 2025-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0009_rename_proposal_function_key_provisionhistory_function_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedRegions',
            fields=[
                ('region_name', models.TextField(primary_key=True, serialize=False)),
                ('is_recognized', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='registration',
            new_name='registered_at',
        ),
    ]
