# Generated by Django 5.2.4 on 2025-07-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0010_recognizedregions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitution',
            name='amendment_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
