# Generated by Django 5.2.4 on 2025-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0011_alter_constitution_amendment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionhistory',
            name='is_judge_vetoable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='is_political_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_judiciary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votingrules',
            name='name_of_government',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='votingrules',
            name='name_of_judiciary',
            field=models.TextField(default=''),
        ),
    ]
