# Generated by Django 5.2.4 on 2025-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0012_provisionhistory_is_judge_vetoable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionhistory',
            name='has_been_challenged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionhistory',
            name='is_in_judicial_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='is_elected_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votingrules',
            name='allowed_open_proposals',
            field=models.SmallIntegerField(default=10),
        ),
    ]
