# Generated by Django 5.2.4 on 2025-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0013_provisionhistory_has_been_challenged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudicialChallenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('was_constitutional', models.BooleanField(blank=True, null=True)),
                ('challenged_proposal_number', models.IntegerField()),
                ('judicial_poll_id', models.TextField()),
            ],
        ),
    ]
