# Generated by Django 5.2.4 on 2025-07-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0014_judicialchallenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='judicialchallenges',
            name='proposed_by_id',
            field=models.TextField(default='1394740210947985458'),
        ),
    ]
