# Generated by Django 5.2.4 on 2025-07-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0015_judicialchallenges_proposed_by_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='id',
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
