# Generated by Django 5.2.4 on 2025-07-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0016_remove_roles_id_alter_roles_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.TextField(default='gug'),
        ),
    ]
