# Generated by Django 5.2.4 on 2025-07-31 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0017_alter_roles_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectedOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('user_name', models.TextField()),
                ('role_id', models.TextField()),
                ('role_name', models.TextField()),
                ('last_election', models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 31, 53, 296647, tzinfo=datetime.timezone.utc))),
                ('last_vote_of_no_confidence', models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 31, 53, 296676, tzinfo=datetime.timezone.utc))),
                ('in_primary', models.BooleanField(default=False)),
                ('in_election', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='roles',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
