# Generated by Django 5.2.4 on 2025-08-05 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0018_electedofficials_roles_salary_users_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='constitution',
            name='has_been_challenged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judicialchallenges',
            name='is_for_existing_amendment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judicialchallenges',
            name='pinged_for_last_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='electedofficials',
            name='last_election',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='electedofficials',
            name='last_vote_of_no_confidence',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
