# Generated by Django 5.2.4 on 2025-08-10 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0019_constitution_has_been_challenged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_item', models.TextField()),
                ('purchaser_id', models.TextField()),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost_at_time_of_purchase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('role_id', models.TextField()),
                ('is_elected_position', models.BooleanField()),
                ('position_expires_at', models.DateTimeField()),
                ('action_when_expires', models.SmallIntegerField(default=0)),
                ('last_election', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_vote_of_no_confidence', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('in_primary', models.BooleanField(default=False)),
                ('in_election', models.BooleanField(default=False)),
                ('money_to_be_charged', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ElectedOfficials',
        ),
        migrations.RenameField(
            model_name='judicialchallenges',
            old_name='proposed_by_id',
            new_name='challenged_by_id',
        ),
        migrations.AddField(
            model_name='judicialchallenges',
            name='original_proposer_name',
            field=models.TextField(default='Quinten E. Democracybot'),
        ),
        migrations.AlterField(
            model_name='users',
            name='registered_at',
            field=models.TextField(default='Schmuckserver'),
        ),
    ]
