# Generated by Django 5.2.4 on 2025-08-12 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0020_purchaselog_temporaryposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField()),
                ('transactor_id', models.TextField()),
                ('transacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseLog',
        ),
        migrations.AddField(
            model_name='roles',
            name='term_length_days',
            field=models.IntegerField(default=14, null=True),
        ),
        migrations.AddField(
            model_name='votingrules',
            name='ubi_amount',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='roles',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
