# Generated by Django 5.2.5 on 2025-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0021_transactionlog_delete_purchaselog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transacted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
