# Generated by Django 5.2.5 on 2025-08-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0022_alter_transactionlog_transacted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transacted_at',
            field=models.DateTimeField(),
        ),
    ]
