from _init import *

SCHMUCKSERVER_ID: int = 0 #REDACTED
VOTING_BOOTH_ID: int = 0 #REDACTED
JUDICIAL_REVIEW_ID: int = 0 #REDACTED
AGENDA_ID: int = 0 #REDACTED
ROTUNDA_ID: int = 0 #REDACTED
WARNING_CHANNEL_ID: int = 0 #REDACTED
VOTER_ROLE_ID: int = 0 #REDACTED
JUDICIARY_ROLE_ID: int = 0 #REDACTED
HIGH_ROLE_ID: int = 0 #REDACTED
POPE_ROLE_ID: int = 0 #REDACTED
BLESSED_ROLE_ID: int = 0 #REDACTED
GOD_KING_USER_ID: int = 0 #REDACTED
DEMOCRACYBOT_USER_ID: int = 0 #REDACTED